"""baseline schema

Revision ID: 5c15a1fe35aa
Revises: 
Create Date: 2026-05-09 14:13:09.708765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c15a1fe35aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('receipts_used_this_month', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.String(length=10), nullable=True),
    sa.Column('paymongo_customer_id', sa.String(length=100), nullable=True),
    sa.Column('paymongo_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tin', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('software', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_user_id'), ['user_id'], unique=False)

    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transactions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_items_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('receipt_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('vendor_tin', sa.String(length=25), nullable=True),
    sa.Column('or_number', sa.String(length=100), nullable=True),
    sa.Column('si_number', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('vat_type', sa.String(length=20), nullable=True),
    sa.Column('vatable_amount', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    with op.batch_alter_table('receipt_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_data_id'), ['id'], unique=False)

    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('requires_2307', sa.String(length=5), nullable=False),
    sa.Column('form_2307_status', sa.String(length=20), nullable=False),
    sa.Column('form_2307_file_path', sa.String(length=500), nullable=True),
    sa.Column('form_2307_original_name', sa.String(length=255), nullable=True),
    sa.Column('form_2307_mime_type', sa.String(length=100), nullable=True),
    sa.Column('form_2307_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('form_2307_requested_at', sa.DateTime(), nullable=True),
    sa.Column('form_2307_received_at', sa.DateTime(), nullable=True),
    sa.Column('form_2307_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliations_bank_transaction_id'), ['bank_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliations_user_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_client_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_bank_transaction_id'))

    op.drop_table('reconciliations')
    with op.batch_alter_table('receipt_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_data_id'))

    op.drop_table('receipt_data')
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_items_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_line_items_id'))

    op.drop_table('line_items')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_client_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_client_id'))

    op.drop_table('bank_transactions')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_user_id'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
