"""add client upload links

Revision ID: c6cda2519628
Revises: 5c15a1fe35aa
Create Date: 2026-05-09 14:35:55.816804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cda2519628'
down_revision: Union[str, None] = '5c15a1fe35aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_upload_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('max_uploads', sa.Integer(), nullable=True),
    sa.Column('uploads_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_upload_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_upload_links_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_upload_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_upload_links_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_upload_links_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_upload_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_upload_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_upload_links_token'))
        batch_op.drop_index(batch_op.f('ix_client_upload_links_id'))
        batch_op.drop_index(batch_op.f('ix_client_upload_links_client_id'))

    op.drop_table('client_upload_links')
    # ### end Alembic commands ###
